### ISSUE TITLE
Deployment guide feedback

### ISSUE THREAD

**Issue by BoPeng** [aws-ia/cfn-ps-illumina-dragen#29]
On page https://aws-ia.github.io/cfn-ps-illumina-dragen/#_feedback

Section heading: Costs and licenses

Documentation issue description:

There is no cost to use this Partner Solution, but you will be billed for any AWS services or resources that this Partner Solution deploys.

But the AMI has a $15 / hr charge for the use of software.

**Comment by vsnyc** [comment]
Apologies, I mistook this issue to be the one that you created the PR for. 

All Quick Starts are open source and there is no cost to using the open sourced CloudFormation templates and scripts. The resources that you deploy as part of the solution including any Marketplace components and other AWS Services will be billed. In other words, yes, you will have to pay the documented hourly cost for the DRAGEN AMI as documented in the Marketplace listing page. We link to it, but don't include that information inline in the deployment guide to avoid inconsistencies.

Below is the full text in the deployment guide.

> There is no cost to use this Partner Solution, but you will be billed for any AWS services or resources that this Partner Solution deploys. For more information, refer to the [AWS Partner Solution General Information Guide](https://fwd.aws/rA69w?).
> 
> This Quick Start requires a subscription to the Amazon Machine Image (AMI) for [DRAGEN Complete Suite](https://aws.amazon.com/marketplace/pp/B07CZ3F5HY), which is available with per-hour pricing from AWS Marketplace.
>
