### ISSUE TITLE
Deployment Guide error

### ISSUE THREAD

**Issue by srx3001** [aws-ia/cfn-ps-illumina-dragen#37]
Hey all, I am facing some issues with dragen deployment using the guide here - https://aws-ia.github.io/cfn-ps-illumina-dragen/.
I have done this before, but its been some time I and don't remember having this problem.
I just ran with "deploy in new VPC" link, here are my parameters, as seen on CloudFormation stack. 

![image](https://github.com/aws-ia/cfn-ps-illumina-dragen/assets/21275401/7516a455-af7c-46b7-84e7-5f8eebfc12c6)

But I keep getting the following error 

![image](https://github.com/aws-ia/cfn-ps-illumina-dragen/assets/21275401/9df21204-3445-4890-8023-66bc47fd5cd8)

It looks like it fails to copy something into the bucket (or cant find source/destination?).

Since its a relatively fresh account and I didn't specify anything extra in template creation, such as IAM (I just left it empty), its strange that it fails here.

Could it be its missing from source for copying?
What direction can I take for this?

Thanks!

**Comment by theodorc** [comment]
I'm encountering the same issue with lambda runtime at python 3.7 and I think updating it to 3.12 will fix it.  Just wondering if the code update will happen.  Thank you.
